#
# Nightstand with added 12v RGB LED strips on a TP-Link Smart Wifi Plug Mini
#
# @link https://home-assistant.io/components/switch.tplink/
#
- platform: tplink
  name: Nightstand Light
  host: !secret tplink_nightstand_light_host
