#
# 12v warm white 100-LED string fairy lights on a TP-Link Smart Wifi Plug Mini
#
# @link https://www.tp-link.com/ca/products/details/cat-5516_HS105.html
# @link https://home-assistant.io/components/switch.tplink/
#
- platform: tplink
  name: Souvenirs Light
  host: !secret tplink_souvenirs_light_host
