#
# Flic smart button
#
# This points to the local flicd daemon that handles the actual Flic buttons.
#
# @link https://flic.io/
# @link https://github.com/pschmitt/hassio-addons/tree/master/flicd
# @link https://home-assistant.io/components/binary_sensor.flic/
#
- platform: flic
  host: !secret flic_host
  port: !secret flic_port
  discovery: true
  timeout: 3
