#
# Pushover notification service for cellphones and tablets
#
# @link https://pushover.net/
# @link https://home-assistant.io/components/notify.pushover/
#
- platform: pushover
  name: Pushover
  api_key: !secret pushover_api_key
  user_key: !secret pushover_user_key
