#
# LIFX cloud scenes
#
# @see /lights/lifx.yaml
#
# @link https://api.developer.lifx.com/docs/list-scenes
# @link https://home-assistant.io/components/scene.lifx_cloud/
#
- platform: lifx_cloud
  token: !secret lifx_cloud_token
  timeout: 10
