#
# Setup basic location information
#
homeassistant:
  name: Home
  latitude: !secret zone_home_latitude
  longitude: !secret zone_home_longitude
  elevation: !secret zone_home_elevation
  unit_system: metric
  time_zone: America/Toronto
  customize_glob: !include customize_glob.yaml
  customize: !include customize.yaml

#
# Log some details
#
# @link https://home-assistant.io/components/frontend/
#
logger:
  default: warning
  logs:
    homeassistant.components.ebox: debug

#
# Enable the official UI
#
# @link https://home-assistant.io/components/frontend/
#
frontend:
  extra_html_url:
    - /local/custom_ui/state-card-custom-ui.html
    - /local/custom_ui/state-card-hline.html
    - /local/custom_ui/state-card-value_only.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-custom-ui-es5.html
    - /local/custom_ui/state-card-hline.html
    - /local/custom_ui/state-card-value_only.html

#
# Enable the configuration UI
#
# @link https://home-assistant.io/components/config/
#
config:

#
# Enable the web server
#
# @link https://home-assistant.io/components/http/
#
http:
  # api_password: !secret http_password
  # base_url: example.duckdns.org:8123

#
# Check for available updates
#
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# Optionally allow Home Assistant developers to focus on popular components.
#
# @link https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
# @link https://home-assistant.io/components/updater/
#
updater:
  include_used_components: true

#
# Discover some devices automatically
#
# @link https://home-assistant.io/components/discovery/
#
discovery:
  ignore:
    - plex_mediaserver

#
# Allow you to issue voice commands from the frontend in enabled browsers
#
# @link https://home-assistant.io/components/conversation/
#
conversation:

#
# Enable support for tracking state changes over time
#
# @link https://home-assistant.io/components/history/
#
history:

#
# View all events in a logbook
#
# @link https://home-assistant.io/components/logbook/
#
logbook:

#
# Enable a map showing the location of tracked devices
#
# @link https://home-assistant.io/components/map/
#
map:

#
# Track the sun
#
# @link https://home-assistant.io/components/sun/
#
sun:

#
# MQTT Integration
#
# @link https://home-assistant.io/components/mqtt/
#
mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password

#
# Text to speech
#
# @link https://home-assistant.io/components/tts/
#
tts:
  - platform: google


#
# Extra configurations
#

#
# Enable the Hass.io panel
#
hassio:

#
# IFTTT integration
#
# @link https://home-assistant.io/components/ifttt/
#
ifttt:
  key: !secret ifttt_key

#
# Device tracking
#
# @link https://home-assistant.io/components/device_tracker/
#
# device_tracker:
#   - platform: owntracks
#   - platform: unifi
#     host: !secret unifi_host
#     port: !secret unifi_port
#     username: !secret unifi_username
#     password: !secret unifi_password
#     verify_ssl: false
#     track_new_devices: false
#     interval_seconds: 10
#     consider_home: 180

#
# Enable the UI customizer
#
# @link https://github.com/andrey-git/home-assistant-customizer
#
customizer:
  custom_ui: local

#
# Database recorder
#
# Reduce the number of tracked entities and length of history.
#
# @link https://home-assistant.io/components/recorder/
#
recorder:
  purge_interval: 2
  purge_keep_days: 5
  exclude:
    domains:
      - camera
      - group
      - light
      - scene
      - script
      - sensor
      - sun
      - updater
      - zone
      - zwave
    entities:
      - switch.aeotec_zstick_disco_light
  include:
    entities:
      - sensor.aqi
      - sensor.aqi_carbon_monoxide
      - sensor.aqi_carbon_monoxide_friendly
      - sensor.aqi_friendly
      - sensor.aqi_nitrogen_dioxide
      - sensor.aqi_nitrogen_dioxide_friendly
      - sensor.aqi_ozone
      - sensor.aqi_ozone_friendly
      - sensor.aqi_particles
      - sensor.aqi_particles_friendly
      - sensor.average_humidity
      - sensor.average_humidity_friendly
      - sensor.average_temperature
      - sensor.bedroom_humidity
      - sensor.bedroom_temperature
      - sensor.lounge_humidity
      - sensor.lounge_luminance
      - sensor.lounge_temperature
      - sensor.outside_humidity
      - sensor.outside_temperature
      - sensor.uv
      - sensor.uv_friendly
      - sensor.wind_speed

#
# ZWave integration
#
# @link https://home-assistant.io/components/zwave/
#
zwave:
  usb_path: /dev/ttyACM0

#
# Modular configuration
#
automation: !include_dir_merge_list automations/
binary_sensor: !include misc/binary_sensors.yaml
camera: !include_dir_merge_list cameras/
input_boolean: !include misc/input_booleans.yaml
input_select: !include misc/input_selects.yaml
light: !include_dir_merge_list lights/
group: !include_dir_merge_named groups/
media_player: !include misc/media_players.yaml
notify: !include_dir_merge_list notifications/
scene: !include_dir_merge_list scenes/
script: !include_dir_merge_named scripts/
sensor: !include_dir_merge_list sensors/
shell_command: !include misc/shell_commands.yaml
switch: !include_dir_merge_list switches/
variable: !include misc/variables.yaml
zone: !include_dir_list zones/
