#
# Atomations
#
# @link https://home-assistant.io/components/automation/
#
automation: !include_dir_merge_list automations/


#
# Binary sensors
#
# @link https://home-assistant.io/components/binary_sensor/
#
binary_sensor: !include misc/binary_sensors.yaml


#
# Cameras
#
# @link https://home-assistant.io/components/camera/
#
camera: !include_dir_merge_list cameras/


#
# Enable the configuration UI
#
# @link https://home-assistant.io/components/config/
#
config:


#
# Allow you to issue voice commands from the frontend in enabled browsers
#
# @link https://home-assistant.io/components/conversation/
#
# conversation:


#
# Enable the UI customizer
#
# @link https://github.com/andrey-git/home-assistant-customizer
#
# customizer:
#   custom_ui: local


#
# Device trackers
#
# @link https://home-assistant.io/components/device_tracker/
#
device_tracker: !include misc/device_trackers.yaml


#
# Discover some devices automatically
#
# @link https://home-assistant.io/components/discovery/
#
discovery:


#
# Displays
#
# @see /custom_components/display/
#
# @link https://github.com/daemondazz/homeassistant-displays
#
display: !include misc/displays.yaml


#
# Enable the official UI
#
# @link https://home-assistant.io/components/frontend/
#
frontend:
  # javascript_version: latest
  extra_html_url:
    - /local/custom_ui/state-card-custom-ui.html
    - /local/custom_ui/state-card-hline.html
    - /local/custom_ui/state-card-value_only.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-custom-ui-es5.html
    - /local/custom_ui/state-card-hline.html
    - /local/custom_ui/state-card-value_only.html
  themes: !include_dir_named themes/


#
# Combine entities into groups and organize UI
#
# @link https://home-assistant.io/components/group/
#
group: !include_dir_merge_named groups/


#
# Enable the Hass.io panel
#
# hassio:


#
# Enable support for tracking state changes over time
#
# @link https://home-assistant.io/components/history/
#
# history:


#
# Setup basic Home Assistant information
#
homeassistant:
  name: Home
  latitude: !secret zone_home_latitude
  longitude: !secret zone_home_longitude
  elevation: !secret zone_home_elevation
  unit_system: metric
  time_zone: America/Toronto
  customize_glob: !include customize_glob.yaml
  customize: !include customize.yaml
  whitelist_external_dirs:
    - /config

#
# Enable the web server
#
# @link https://home-assistant.io/components/http/
#
http:
  # api_password: !secret http_password
  # base_url: !secret http_base_url
  cors_allowed_origins:
    - http://hassio.local:5050

#
# IFTTT integration
#
# @link https://home-assistant.io/components/ifttt/
#
# ifttt:
#   key: !secret ifttt_key


#
# Input booleans
#
# @link https://home-assistant.io/components/input_boolean/
#
input_boolean: !include misc/input_booleans.yaml


#
# Lists of selectable values
#
# @link https://home-assistant.io/components/input_select/
#
input_select: !include misc/input_selects.yaml


#
# iOS companion component for the  Home Assistant iOS app
#
# @link https://itunes.apple.com/us/app/home-assistant-open-source-home-automation/id1099568401
# @link https://home-assistant.io/docs/ecosystem/ios/
#
ios:


#
# Lights
#
# @link https://home-assistant.io/components/light/
#
light: !include_dir_merge_list lights/


#
# View all events in a logbook
#
# @link https://home-assistant.io/components/logbook/
#
# logbook:


#
# Log some details
#
# @link https://home-assistant.io/components/logger/
#
logger:
  default: warning
  logs:
    custom_components.display: critical
    homeassistant.components.notify.lannouncer: debug
    # homeassistant.light.rest: critical
    # homeassistant.sensor.ebox: debug
    # custom_components.sensor.ebox: debug


#
# Enable a map showing the location of tracked devices
#
# @link https://home-assistant.io/components/map/
#
# map:


#
# Media players
#
# @link https://home-assistant.io/components/media_player/
#
media_player: !include misc/media_players.yaml


#
# MQTT Integration
#
# @link https://home-assistant.io/components/mqtt/
#
mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password


#
# Notification services
#
# @link https://home-assistant.io/components/notify/
#
notify: !include_dir_merge_list notifications/


#
# Database recorder
#
# Reduce the number of tracked entities and length of history.
#
# @link https://home-assistant.io/components/recorder/
#
recorder:
  purge_interval: 2
  purge_keep_days: 5
  exclude:
    domains:
      - camera
      - group
      - light
      - scene
      - script
      - sensor
      - sun
      - updater
      - zone
      - zwave
    entities:
      - switch.aeotec_zstick_disco_light
  include:
    entities:
      - sensor.aqi
      - sensor.aqi_carbon_monoxide
      - sensor.aqi_carbon_monoxide_friendly
      - sensor.aqi_friendly
      - sensor.aqi_nitrogen_dioxide
      - sensor.aqi_nitrogen_dioxide_friendly
      - sensor.aqi_ozone
      - sensor.aqi_ozone_friendly
      - sensor.aqi_particles
      - sensor.aqi_particles_friendly
      - sensor.average_humidity
      - sensor.average_humidity_friendly
      - sensor.average_temperature
      - sensor.bedroom_humidity
      - sensor.bedroom_temperature
      - sensor.lounge_humidity
      - sensor.lounge_luminance
      - sensor.lounge_temperature
      - sensor.outside_humidity
      - sensor.outside_temperature
      - sensor.uv
      - sensor.uv_friendly
      - sensor.wind_speed


#
# Scenes
#
# @link https://home-assistant.io/components/scene/
#
scene: !include misc/scenes.yaml


#
# Scripts
#
# @link https://home-assistant.io/components/script/
#
script: !include_dir_named scripts/


#
# Sensors
#
# @link https://home-assistant.io/components/sensor/
#
sensor: !include_dir_merge_list sensors/


#
# Shell commands
#
# @link https://home-assistant.io/components/shell_command/
#
shell_command: !include misc/shell_commands.yaml


#
# Track the sun
#
# @link https://home-assistant.io/components/sun/
#
sun:


#
# Switches
#
# @link https://home-assistant.io/components/switch/
#
switch: !include_dir_merge_list switches/


#
# Text to speech
#
# @link https://home-assistant.io/components/tts/
#
tts:
  - platform: google


#
# Check for available updates
#
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# Optionally allow Home Assistant developers to focus on popular components.
#
# @link https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
# @link https://home-assistant.io/components/updater/
#
updater:
  include_used_components: true


#
# Variables
#
# @see /custom_components/variable.py
#
# @link https://github.com/rogro82/hass-variables
#
variable: !include misc/variables.yaml


#
# Zones
#
# @link https://home-assistant.io/components/zone/
#
zone: !include misc/zones.yaml


#
# ZWave integration
#
# @link https://home-assistant.io/docs/z-wave/adding/
# @link https://home-assistant.io/docs/z-wave/
# @link https://home-assistant.io/components/zwave/
#
zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_network_key
