#
# LimitlessLED smart light for MiLight devices
#
# @see /automations/cct.yaml
#
# @link http://www.limitlessled.com/
# @link https://www.futlight.com/productdetails.aspx?id=293&typeid=146
# @link https://www.futlight.com/productdetails.aspx?id=239&typeid=125
# @link http://www.milight.com/milight-wifi-box/
# @link https://home-assistant.io/components/light.limitlessled/
#
- platform: limitlessled
  bridges:
    - host: !secret limitleddled_bridge_host
      port: !secret limitleddled_bridge_port
      groups:
      - number: 4
        type: white
        name: Island
        fade: on
      - number: 1
        type: white
        name: Countertop
        fade: on
      - number: 2
        type: white
        name: Sink
        fade: on
      - number: 3
        type: white
        name: Microwave
        fade: on
