#
# View
#
configuration_view:
  view: yes
  name: Configuration
  icon: mdi:settings
  entities:
    - group.modes
    - group.automations
    - group.automations_modes
    - group.automations_devices
    - group.automations_areas
    - group.configuration_switches


#
# Groups
#
modes:
  name: Modes
  control: hidden
  entities:
    - input_boolean.night_mode
    - input_boolean.nap_mode
    - input_boolean.quiet_mode
    - input_boolean.low_mode
    - input_boolean.scene_mode
    - input_boolean.motion_detected
    - input_boolean.tamper_detected
    - variable.tamper_detected

automations:
  name: Automations
  control: hidden
  entities:
    - automation.cct_lifx
    - automation.cct_limitlessled
    - automation.daily_greeting
    - automation.doors_notify
    - automation.doors_verify
    - automation.front_door_notify
    - automation.go_to_sleep
    - automation.humidity_notify
    - automation.scene_daylight
    - automation.scene_gaming
    - automation.scene_romantic
    - automation.scene_select
    - automation.tamper_detection_notify
    - automation.theme_auto
    - automation.update_notify
    - automation.wake_up

automations_areas:
  name: Areas Automations
  control: hidden
  entities:
    - automation.bedroom_low_power
    - automation.bedroom_off
    - automation.bedroom_on
    - automation.ceiling_effect
    - automation.ceiling_off
    - automation.ceiling_on
    - automation.ceiling_schedule
    - automation.ceiling_select
    - automation.kitchen_low_power
    - automation.kitchen_off
    - automation.kitchen_on
    - automation.lounge_low_power
    - automation.lounge_off
    - automation.lounge_on
    - automation.washroom_low_power
    - automation.washroom_off
    - automation.washroom_on

automations_devices:
  name: Devices Automations
  control: hidden
  entities:
    - automation.aurora_brightness
    - automation.aurora_effect
    - automation.aurora_schedule
    - automation.aurora_select
    - automation.bed_effect
    - automation.bed_schedule
    - automation.bed_select
    - automation.dehumidifier_off
    - automation.dehumidifier_on
    - automation.kitchen_lights_full
    - automation.kitchen_lights_init
    - automation.kitchen_lights_off
    - automation.kitchen_lights_on
    - automation.kitchen_lights_toggle
    - automation.kiosk_auto
    - automation.kiosk_low_power
    - automation.lightpack_effect
    - automation.lightpack_select
    - automation.nightlight_off
    - automation.nightlight_on
    - automation.scene_effect
    - automation.video_player_resume
    - automation.video_player_stop

automations_modes:
  name: Modes Automations
  control: hidden
  entities:
    - automation.low_power_mode_start
    - automation.low_power_mode_stop
    - automation.motion_detection_auto
    - automation.nap_mode_start
    - automation.nap_mode_stop
    - automation.night_mode_start
    - automation.night_mode_stop
    - automation.quiet_mode_start
    - automation.quiet_mode_stop
    - automation.tamper_detection_start
    - automation.tamper_detection_stop

configuration_switches:
  name: Configuration Switches
  control: hidden
  entities:
    - switch.aeotec_zstick_disco_light
    - script.tamper_reset
