#
# View
#
default_view:
  view: yes
  icon: mdi:home-assistant
  entities:
    - group.notifications
    - group.wallpaper
    - group.now
    - group.public_transit
    - group.climate
    - group.actions
    - group.security


#
# Groups
#
actions:
  name: Actions
  control: hidden
  entities:
    - script.wake_up
    - input_select.scene
    - input_boolean.night_mode
    - input_boolean.nap_mode
    - input_boolean.quiet_mode
    - input_boolean.low_mode

climate:
  name: Climate Control
  entities:
    - sensor.average_temperature
    - sensor.average_humidity_friendly
    - switch.dehumidifier

notifications:
  name: Notifications
  entities:
    - persistent_notification.humidity

now:
  name: " "
  entities:
    - sensor.date_friendly
    - sensor.time_friendly
    - sensor.sun_state

public_transit:
  name: Public Transit
  entities:
    - sensor.home_to_metro_hour
    - sensor.home_to_metro_2_hour
    - sensor.home_to_metro_3_hour
    - sensor.home_to_market_hour
    - sensor.home_to_market_2_hour
    - sensor.home_to_market_3_hour

wallpaper:
  name: " "
  entities:
    - camera.bing_wallpaper
    - sensor.bing_wallpaper_info

security:
  name: Security Status
  control: hidden
  entities:
    - sensor.doors_status
    - sensor.motion_status
    - sensor.tamper_status
