#
# Time & Date
#
# Manipulates time and dates to make them more human-friendly.
#
# @link https://home-assistant.io/components/sensor.time_date/
#
- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'time_date'

- platform: template
  sensors:
    date_friendly:
      friendly_name: Date
      icon_template: mdi:calendar-today
      friendly_name_template: >-
        {% set date = states('sensor.date') %}
        {% set datetime = strptime(date, '%Y-%m-%d') %}
        {{ datetime.strftime('%A') }}
      value_template: >-
        {# Using a sensor instead of now() to avoid constant updating. #}
        {% set date = states('sensor.date') %}
        {% set datetime = strptime(date, '%Y-%m-%d') %}

        {% set month = datetime.strftime('%B') %}
        {% set day = datetime.strftime('%d') | int %}
        {%
          set suffix = "st" if (day % 10 == 1 and day != 11)
          else "nd" if (day % 10 == 2 and day != 12)
          else "rd" if (day % 10 == 3 and day != 13)
          else "th"
        %}

        {{ month }} {{ day }}

    time_friendly:
      friendly_name: Time
      icon_template: mdi:clock
      value_template: >-
        {% set hour = states('sensor.time').split(':')[0] | int %}
        {% set minutes = states('sensor.time').split(':')[1] %}

        {{ hour }}:{{ minutes }}

    after_tomorrow:
      friendly_name: After Tomorrow
      value_template: >-
        {# Using a sensor instead of now() to avoid constant updating. #}
        {% set date = states('sensor.date') %}
        {% set datetime = strptime(date, '%Y-%m-%d') %}
        {% set timestamp = as_timestamp(datetime) + 2*24*60*60 %}

        {{ timestamp | timestamp_custom('%A') }}


#
# Number of days in a month
#
# Used to calculate remaining bandwidth capacity from ISP.
#
# @see /sensors/isp.yaml
#
- platform: template
  sensors:
    days_in_month:
      friendly_name: Days in Month
      icon_template: mdi:calendar
      value_template: >-
        {# Using a sensor instead of now() to avoid constant updating. #}
        {% set date = states('sensor.date') %}
        {% set datetime = strptime(date, '%Y-%m-%d') %}
        {% set month = datetime.month %}
        {% set year = datetime.year %}
        {% set days = 31 if month in [1,3,5,7,8,10,12]
          else 30 if month in [4,6,9,11]
          else 29 if as_timestamp(strptime(year|string + '-02-29', "%Y-%m-%d"))
          else 28
        %}

        {{ days }}

    days_remaining_in_month:
      friendly_name: Days Remaining in Month
      icon_template: mdi:calendar
      value_template: >-
        {% set days_in_month = states('sensor.days_in_month') | int %}

        {{ days_in_month - now().day }}


#
# Report on the next sun event (risings or settings)
#
- platform: template
  sensors:
    sun_state:
      friendly_name: Sun
      icon_template: >-
        {% if is_state('sun.sun', 'above_horizon') %}
          mdi:weather-sunny
        {% else %}
          mdi:weather-night
        {% endif %}
      value_template: >-
        {% if is_state('sun.sun', 'above_horizon') %}
          sets at {% set timestamp = as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom("%H:%M") %} {{ timestamp.lstrip("0") }}
        {% else %}
          rises at {% set timestamp = as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom("%H:%M") %} {{ timestamp.lstrip("0") }}
        {% endif %}
