#
# Bedroom climate
#
# Calibration offsets:
#   Humidity: -1.5%
#   Temperature: +0.2°C
#
- platform: mqtt
  name: Bedroom AcuRite
  state_topic: "home/Acurite_tower_sensor/11846"

- platform: mqtt
  name: Bedroom Humidity Exact
  state_topic: "home/Acurite_tower_sensor/11846"
  unit_of_measurement: '%'
  value_template: >-
    {% set calibration = -1.5 %}
    {% set humidity = value_json.humidity %}

    {{ humidity + calibration }}

- platform: mqtt
  name: Bedroom Temperature Exact
  state_topic: "home/Acurite_tower_sensor/11846"
  unit_of_measurement: '°C'
  value_template: >-
    {% set calibration = 0.2 %}
    {% set temperature = value_json.temperature_C %}

    {{ (temperature + calibration) | round(1) }}

- platform: template
  sensors:
    bedroom_humidity:
      friendly_name: Bedroom Humidity
      unit_of_measurement: '%'
      icon_template: mdi:water-percent
      value_template: "{{ states('sensor.bedroom_humidity_exact') | round }}"

    bedroom_temperature:
      friendly_name: Bedroom Humidity
      unit_of_measurement: '°C'
      icon_template: mdi:thermometer
      value_template: "{{ states('sensor.bedroom_temperature_exact') | round }}"

- platform: filter
  name: Bedroom Humidity Filtered
  entity_id: sensor.bedroom_humidity_exact
  filters:
    - filter: lowpass
      time_constant: 10
      precision: 1

- platform: filter
  name: Bedroom Temperature Filtered
  entity_id: sensor.bedroom_temperature_exact
  filters:
    - filter: lowpass
      time_constant: 10
      precision: 1


#
# Lounge climate
#
# Calibration offsets (set through Zwave configuration panel):
#   Humidity: +5.0% (5)
#   Temperature: -1.1°C (256-11 = 245 = 0xF5 -> +0x01 = 0xF501 = 62721 -> -65536 = -2815)
#
# @link https://www.tabsoverspaces.com/233657-calibrating-aeotec-multisensor-6s-temperature-using-openzwave-in-domoticz/
#
- platform: template
  sensors:
    lounge_humidity_exact:
      friendly_name: Lounge Humidity Exact
      unit_of_measurement: '%'
      icon_template: mdi:water-percent
      value_template: "{{ states('sensor.lounge_multisensor_relative_humidity') }}"

    lounge_humidity:
      friendly_name: Lounge Humidity
      unit_of_measurement: '%'
      icon_template: mdi:water-percent
      value_template: "{{ states('sensor.lounge_multisensor_relative_humidity') | round }}"

    lounge_temperature_exact:
      friendly_name: Lounge Temperature Exact
      unit_of_measurement: '°C'
      icon_template: mdi:thermometer
      value_template: "{{ states('sensor.lounge_multisensor_temperature') }}"

    lounge_temperature:
      friendly_name: Lounge Temperature
      unit_of_measurement: '°C'
      icon_template: mdi:thermometer
      value_template: "{{ states('sensor.lounge_multisensor_temperature') | round }}"

    lounge_luminance:
      friendly_name: Lounge Luminance
      unit_of_measurement: 'lx'
      icon_template: mdi:blur
      value_template: "{{ states('sensor.lounge_multisensor_luminance') | round }}"

- platform: filter
  name: Lounge Humidity Filtered
  entity_id: sensor.lounge_humidity_exact
  filters:
    - filter: lowpass
      time_constant: 10
      precision: 1

- platform: filter
  name: Lounge Temperature Filtered
  entity_id: sensor.lounge_temperature_exact
  filters:
    - filter: lowpass
      time_constant: 10
      precision: 1


#
# Average temperature
#
# The appartment being mostly open plan, one can calculate an average
# temperature value between calibrated sensors set in different rooms.
#
# Uses the current reading because temperature changes are readily felt.
#
- platform: min_max
  name: Average Temperature Exact
  type: mean
  round_digits: 0
  entity_ids:
    - sensor.bedroom_temperature_exact
    - sensor.lounge_temperature_exact

- platform: template
  sensors:
    average_temperature:
      friendly_name: Temperature
      unit_of_measurement: '°C'
      icon_template: mdi:thermometer
      value_template: "{{ states('sensor.average_temperature_exact') | round }}"


#
# Average humidity
#
# The appartment being mostly open plan, one can calculate an average humidity
# value between calibrated sensors set in different rooms.
#
# Uses the filtered reading because humidity hikes and drops can happen rapidly
# but their real effect is smoothed over time due to humidity absorption and
# release of furniture, fabrics and building materials.
#
- platform: min_max
  name: Average Humidity Exact
  type: mean
  round_digits: 1
  entity_ids:
    - sensor.bedroom_humidity_filtered
    - sensor.lounge_humidity_filtered

- platform: template
  sensors:
    average_humidity:
      friendly_name: Humidity
      unit_of_measurement: '%'
      icon_template: mdi:water-percent
      value_template: "{{ states('sensor.average_humidity_exact') | round }}"

- platform: template
  sensors:
    average_humidity_friendly:
      friendly_name: Humidity
      icon_template: mdi:water-percent
      value_template: >-
        {% set humidity = states('sensor.average_humidity') | int %}

        {% if humidity > 90 %}
          Mold imminent
        {% elif humidity > 70 %}
          Mold alert
        {% elif humidity > 55 %}
          Mold warning
        {% elif humidity > 50 %}
          OK-High
        {% elif humidity > 35 %}
          OK
        {% elif humidity >= 30 %}
          OK-Low
        {% else %}
          Too dry
        {% endif %}
