#
# Bedroom climate
#
- platform: mqtt
  name: Bedroom AcuRite
  state_topic: "home/bedroom/bedroom"

- platform: mqtt
  name: Bedroom Humidity
  state_topic: "home/bedroom/bedroom"
  unit_of_measurement: '%'
  value_template: '{{ value_json.humidity | round }}'

- platform: mqtt
  name: Bedroom Temperature
  state_topic: "home/bedroom/bedroom"
  unit_of_measurement: '°C'
  value_template: '{{ value_json.temperature_C | round }}'

#
# Lounge climate
#
- platform: template
  sensors:
    lounge_humidity:
      friendly_name: Lounge Humidity
      unit_of_measurement: '%'
      icon_template: mdi:water-percent
      value_template: "{{ states('sensor.lounge_multisensor_relative_humidity') | round }}"

    lounge_temperature:
      friendly_name: Lounge Temperature
      unit_of_measurement: '°C'
      icon_template: mdi:thermometer
      value_template: "{{ states('sensor.lounge_multisensor_temperature') | round }}"

    lounge_luminance:
      friendly_name: Lounge Luminance
      unit_of_measurement: 'lux'
      icon_template: mdi:blur
      value_template: "{{ states('sensor.lounge_multisensor_luminance') | round }}"


#
# Average temperature
#
# Help compensate for lack of accuracy of each active sensor.
# They all claim to be precise, but precision doesn't mean accuracy!
#
- platform: min_max
  name: Average Temperature Exact
  type: mean
  round_digits: 0
  entity_ids:
    - sensor.lounge_temperature
    - sensor.bedroom_temperature

- platform: template
  sensors:
    average_temperature:
      friendly_name: Temperature
      unit_of_measurement: '°C'
      icon_template: mdi:thermometer
      value_template: "{{ states('sensor.average_temperature_exact') | round }}"


#
# Average humidity
#
# Helps compensate for lack of accuracy of each active sensor.
# They all claim to be precise, but precision doesn't mean accuracy!
#
- platform: min_max
  name: Average Humidity Exact
  type: mean
  round_digits: 1
  entity_ids:
    - sensor.lounge_humidity
    - sensor.bedroom_humidity

- platform: template
  sensors:
    average_humidity:
      friendly_name: Humidity
      unit_of_measurement: '%'
      icon_template: mdi:water-percent
      value_template: "{{ states('sensor.average_humidity_exact') | round }}"

- platform: template
  sensors:
    average_humidity_friendly:
      friendly_name: Humidity
      icon_template: mdi:water-percent
      value_template: >-
        {% set humidity = states('sensor.average_humidity') | int %}

        {% if humidity > 90 %}
          Mold imminent
        {% elif humidity > 70 %}
          Mold alert
        {% elif humidity > 55 %}
          Mold warning
        {% elif humidity > 50 %}
          OK-High
        {% elif humidity > 35 %}
          OK
        {% elif humidity >= 30 %}
          OK-Low
        {% else %}
          Too dry
        {% endif %}
