# Public Transit
- platform: gtfs
  name: 'Home to metro'
  origin: !secret gtfs_origin_1
  destination: !secret gtfs_destination_1
  data: !secret gtfs_data
  scan_interval: 60

- platform: gtfs
  name: 'Home to metro 2'
  origin: !secret gtfs_origin_1
  destination: !secret gtfs_destination_1
  data: !secret gtfs_data
  scan_interval: 65
  position: 2

- platform: gtfs
  name: 'Home to metro 3'
  origin: !secret gtfs_origin_1
  destination: !secret gtfs_destination_1
  data: !secret gtfs_data
  scan_interval: 70
  position: 3

- platform: gtfs
  name: 'Home to groceries'
  origin: !secret gtfs_origin_2
  destination: !secret gtfs_destination_2
  data: !secret gtfs_data
  scan_interval: 60

- platform: gtfs
  name: 'Home to groceries 2'
  origin: !secret gtfs_origin_2
  destination: !secret gtfs_destination_2
  data: !secret gtfs_data
  scan_interval: 65
  position: 2

- platform: gtfs
  name: 'Home to groceries 3'
  origin: !secret gtfs_origin_2
  destination: !secret gtfs_destination_2
  data: !secret gtfs_data
  scan_interval: 70
  position: 3

- platform: template
  sensors:
    home_to_metro_countdown:
      friendly_name: Bus to metro
      icon_template: mdi:bus
      value_template: >-
        {% set countdown = states('sensor.home_to_metro') | int %}
        {% if countdown > 60 %}
          {% set hours = (countdown / 60) | int %}
          {% set minutes = (countdown % 60) | int %}
          {% if minutes < 10 %}
            {% set minutes = '0' + minutes | string %}
          {% endif %}
          {{hours}}:{{minutes}}
        {% else %}
          {{countdown}}
        {% endif %}

    home_to_metro_2_countdown:
      friendly_name: Bus to metro 2
      icon_template: mdi:bus
      value_template: >-
        {% set countdown = states('sensor.home_to_metro_2') | int %}
        {% if countdown > 60 %}
          {% set hours = (countdown / 60) | int %}
          {% set minutes = (countdown % 60) | int %}
          {% if minutes < 10 %}
            {% set minutes = '0' + minutes | string %}
          {% endif %}
          {{hours}}:{{minutes}}
        {% else %}
          {{countdown}}
        {% endif %}

    home_to_metro_3_countdown:
      friendly_name: Bus to metro 3
      icon_template: mdi:bus
      value_template: >-
        {% set countdown = states('sensor.home_to_metro_3') | int %}
        {% if countdown > 60 %}
          {% set hours = (countdown / 60) | int %}
          {% set minutes = (countdown % 60) | int %}
          {% if minutes < 10 %}
            {% set minutes = '0' + minutes | string %}
          {% endif %}
          {{hours}}:{{minutes}}
        {% else %}
          {{countdown}}
        {% endif %}

    home_to_groceries_countdown:
      friendly_name: Bus to groceries
      icon_template: mdi:bus
      value_template: >-
        {% set countdown = states('sensor.home_to_groceries') | int %}
        {% if countdown > 60 %}
          {% set hours = (countdown / 60) | int %}
          {% set minutes = (countdown % 60) | int %}
          {% if minutes < 10 %}
            {% set minutes = '0' + minutes | string %}
          {% endif %}
          {{hours}}:{{minutes}}
        {% else %}
          {{countdown}}
        {% endif %}

    home_to_groceries_2_countdown:
      friendly_name: Bus to groceries 2
      icon_template: mdi:bus
      value_template: >-
        {% set countdown = states('sensor.home_to_groceries_2') | int %}
        {% if countdown > 60 %}
          {% set hours = (countdown / 60) | int %}
          {% set minutes = (countdown % 60) | int %}
          {% if minutes < 10 %}
            {% set minutes = '0' + minutes | string %}
          {% endif %}
          {{hours}}:{{minutes}}
        {% else %}
          {{countdown}}
        {% endif %}

    home_to_groceries_3_countdown:
      friendly_name: Bus to groceries 3
      icon_template: mdi:bus
      value_template: >-
        {% set countdown = states('sensor.home_to_groceries_3') | int %}
        {% if countdown > 60 %}
          {% set hours = (countdown / 60) | int %}
          {% set minutes = (countdown % 60) | int %}
          {% if minutes < 10 %}
            {% set minutes = '0' + minutes | string %}
          {% endif %}
          {{hours}}:{{minutes}}
        {% else %}
          {{countdown}}
        {% endif %}

    home_to_metro_hour:
      friendly_name: Bus to metro
      icon_template: mdi:bus
      value_template: >-
        {% set departure = states.sensor.home_to_metro.attributes['Origin Stop Departure Time'].split(' ') %}
        {% set hms = departure[1].split(':') %}

        {{hms[0]}}:{{hms[1]}}

    home_to_metro_2_hour:
      friendly_name: Bus to metro (Next)
      icon_template: mdi:bus
      value_template: >-
        {% set departure = states.sensor.home_to_metro_2.attributes['Origin Stop Departure Time'].split(' ') %}
        {% set hms = departure[1].split(':') %}

        {{hms[0]}}:{{hms[1]}}

    home_to_metro_3_hour:
      friendly_name: Bus to metro (After)
      icon_template: mdi:bus
      value_template: >-
        {% set departure = states.sensor.home_to_metro_3.attributes['Origin Stop Departure Time'].split(' ') %}
        {% set hms = departure[1].split(':') %}

        {{hms[0]}}:{{hms[1]}}

    home_to_groceries_hour:
      friendly_name: Bus to market
      icon_template: mdi:bus
      value_template: >-
        {% set departure = states.sensor.home_to_groceries.attributes['Origin Stop Departure Time'].split(' ') %}
        {% set hms = departure[1].split(':') %}

        {{hms[0]}}:{{hms[1]}}

    home_to_groceries_2_hour:
      friendly_name: Bus to market (Next)
      icon_template: mdi:bus
      value_template: >-
        {% set departure = states.sensor.home_to_groceries_2.attributes['Origin Stop Departure Time'].split(' ') %}
        {% set hms = departure[1].split(':') %}

        {{hms[0]}}:{{hms[1]}}

    home_to_groceries_3_hour:
      friendly_name: Bus to market (After)
      icon_template: mdi:bus
      value_template: >-
        {% set departure = states.sensor.home_to_groceries_3.attributes['Origin Stop Departure Time'].split(' ') %}
        {% set hms = departure[1].split(':') %}

        {{hms[0]}}:{{hms[1]}}

