#
# Doomsday Clock
#
# see: https://github.com/renemarc/home-assistant-custom-components
# see: https://thebulletin.org/doomsday-dashboard
# see: https://github.com/mattbierner/MinutesToMidnight/blob/master/index.js
#
- platform: doomsday_clock
  scan_interval: 86400


#
# World Air Quality Index (WAQI)
#
# Ratings for templates below are USA ones instead of Canadians.
#
# see: https://en.wikipedia.org/wiki/Air_quality_index
#
- platform: waqi
  token: !secret waqi_token
  locations:
    - !secret waqi_location1
    - !secret waqi_location2


#
# WAQI: Average
#
- platform: min_max
  name: AQI exact
  type: mean
  round_digits: 0
  entity_ids:
    - sensor.waqi_rivesud_de_montreal_quebec_canada
    - sensor.waqi_longueuil__secteur_du_parc_oceanie_brossard_quebec_canada

- platform: template
  sensors:
    aqi:
      friendly_name: Air Quality Index
      icon_template: mdi:chemical-weapon
      entity_id:
        - sensor.aqi_exact
      value_template: >-
        {% set index = states('sensor.aqi_exact') %}

        {% if index != "unknown" %}
          {{ index | float | round }}
        {% else %}
          {{ index }}
        {% endif %}

    aqi_friendly:
      friendly_name: Air Quality Index
      icon_template: mdi:chemical-weapon
      entity_id:
        - sensor.aqi_exact
      value_template: >-
        {% set index = states('sensor.aqi_exact') %}

        {% if index != "unknown" %}
          {% set index = index | float | round %}

          {% if 0 <= index <= 50 %}
            Good
          {% elif 51 <= index <= 100 %}
            Moderate
          {% elif 101 <= index <= 150 %}
            Unhealthy for Sensitive Groups
          {% elif 151 <= index <= 200 %}
            Unhealthy
          {% elif 201 <= index <= 300 %}
            Very Unhealthy
          {% elif 301 <= index %}
            Hazardous
          {% else %}
            N/A
          {% endif %}
        {% endif %}


#
# WAQI: Particulate matter 2.5Î¼m
#
- platform: template
  sensors:
    aqi_particles:
      friendly_name: PM2.5
      icon_template: mdi:factory
      unit_of_measurement: 'PPM'
      entity_id:
        - sensor.waqi_rivesud_de_montreal_quebec_canada
        - sensor.waqi_longueuil__secteur_du_parc_oceanie_brossard_quebec_canada
      value_template: >-
        {% set levels = 0 %}
        {% set counter = 0 %}
        {% if states('sensor.waqi_rivesud_de_montreal_quebec_canada') != "unknown" and states.sensor.waqi_rivesud_de_montreal_quebec_canada.attributes.pm_2_5 is defined %}
          {% set levels = levels + states.sensor.waqi_rivesud_de_montreal_quebec_canada.attributes.pm_2_5 %}
          {% set counter = counter + 1 %}
        {% endif %}
        {% if states('sensor.waqi_longueuil__secteur_du_parc_oceanie_brossard_quebec_canada') != "unknown" and states.sensor.waqi_longueuil__secteur_du_parc_oceanie_brossard_quebec_canada.attributes.pm_2_5 is defined %}
          {% set levels = levels + states.sensor.waqi_longueuil__secteur_du_parc_oceanie_brossard_quebec_canada.attributes.pm_2_5 %}
          {% set counter = counter + 1 %}
        {% endif %}

        {% if counter > 0 %}
          {{ (levels / counter) | round }}
        {% else %}
          unknown
        {% endif %}

    aqi_particles_friendly:
      friendly_name: PM2.5
      icon_template: mdi:factory
      entity_id:
        - sensor.aqi_particles
      value_template: >-
        {% set pm25 = states('sensor.aqi_particles') | int(-1) %}

        {% if pm25 < 0 %}
          unknown
        {% elif 0 <= pm25 <= 50 %}
          Good
        {% elif 51 <= pm25 <= 100 %}
          Moderate
        {% elif 101 <= pm25 <= 150 %}
          Unhealthy for Sensitive Groups
        {% elif 151 <= pm25 <= 200 %}
          Unhealthy
        {% elif 201 <= pm25 <= 300 %}
          Very Unhealthy
        {% elif 301 <= pm25 %}
          Hazardous
        {% else %}
          N/A
        {% endif %}


#
# WAQI: Ozone
#
- platform: template
  sensors:
    aqi_ozone:
      friendly_name: Ozone
      icon_template: mdi:earth
      unit_of_measurement: 'PPM'
      entity_id:
        - sensor.waqi_rivesud_de_montreal_quebec_canada
        - sensor.waqi_longueuil__secteur_du_parc_oceanie_brossard_quebec_canada
      value_template: >-
        {% set levels = 0 %}
        {% set counter = 0 %}
        {% if states('sensor.waqi_rivesud_de_montreal_quebec_canada') != "unknown" and states.sensor.waqi_rivesud_de_montreal_quebec_canada.attributes.ozone is defined %}
          {% set levels = levels + states.sensor.waqi_rivesud_de_montreal_quebec_canada.attributes.ozone %}
          {% set counter = counter + 1 %}
        {% endif %}
        {% if states('sensor.waqi_longueuil__secteur_du_parc_oceanie_brossard_quebec_canada') != "unknown" and states.sensor.waqi_longueuil__secteur_du_parc_oceanie_brossard_quebec_canada.attributes.ozone is defined %}
          {% set levels = levels + states.sensor.waqi_longueuil__secteur_du_parc_oceanie_brossard_quebec_canada.attributes.ozone %}
          {% set counter = counter + 1 %}
        {% endif %}

        {% if counter > 0 %}
          {{ (levels / counter) | round }}
        {% else %}
          unknown
        {% endif %}

    aqi_ozone_friendly:
      friendly_name: Ozone
      icon_template: mdi:earth
      entity_id:
        - sensor.aqi_ozone
      value_template: >-
        {% set ozone = states('sensor.aqi_ozone') | int(-1) %}

        {% if ozone < 0 %}
          unknown
        {% elif 0 <= ozone <= 50 %}
          Good
        {% elif 51 <= ozone <= 100 %}
          Moderate
        {% elif 101 <= ozone <= 150 %}
          Unhealthy for Sensitive Groups
        {% elif 151 <= ozone <= 200 %}
          Unhealthy
        {% elif 201 <= ozone <= 300 %}
          Very Unhealthy
        {% elif 301 <= ozone %}
          Hazardous
        {% else %}
          N/A
        {% endif %}


#
# WAQI: Nitrogen dioxide
#
- platform: template
  sensors:
    aqi_nitrogen_dioxide:
      friendly_name: Nitrogen Dioxide
      icon_template: mdi:car
      unit_of_measurement: 'PPM'
      entity_id:
        - sensor.waqi_rivesud_de_montreal_quebec_canada
        - sensor.waqi_longueuil__secteur_du_parc_oceanie_brossard_quebec_canada
      value_template: >-
        {% set levels = 0 %}
        {% set counter = 0 %}
        {% if states('sensor.waqi_rivesud_de_montreal_quebec_canada') != "unknown" and states.sensor.waqi_rivesud_de_montreal_quebec_canada.attributes.nitrogen_dioxide is defined %}
          {% set levels = levels + states.sensor.waqi_rivesud_de_montreal_quebec_canada.attributes.nitrogen_dioxide %}
          {% set counter = counter + 1 %}
        {% endif %}
        {% if states('sensor.waqi_longueuil__secteur_du_parc_oceanie_brossard_quebec_canada') != "unknown" and states.sensor.waqi_longueuil__secteur_du_parc_oceanie_brossard_quebec_canada.attributes.nitrogen_dioxide is defined %}
          {% set levels = levels + states.sensor.waqi_longueuil__secteur_du_parc_oceanie_brossard_quebec_canada.attributes.nitrogen_dioxide %}
          {% set counter = counter + 1 %}
        {% endif %}

        {% if counter > 0 %}
          {{ (levels / counter) | round }}
        {% else %}
          unknown
        {% endif %}

    aqi_nitrogen_dioxide_friendly:
      friendly_name: Nitrogen Dioxide
      icon_template: mdi:car
      entity_id:
        - sensor.aqi_nitrogen_dioxide
      value_template: >-
        {% set nox = states('sensor.aqi_nitrogen_dioxide') | int(-1) %}

        {% if nox < 0 %}
          unknown
        {% elif 0 <= nox <= 50 %}
          Good
        {% elif 51 <= nox <= 100 %}
          Moderate
        {% elif 101 <= nox <= 150 %}
          Unhealthy for Sensitive Groups
        {% elif 151 <= nox <= 200 %}
          Unhealthy
        {% elif 201 <= nox <= 300 %}
          Very Unhealthy
        {% elif 301 <= nox %}
          Off the Scale
        {% else %}
          N/A
        {% endif %}


#
# WAQI: Carbon monoxide
#
- platform: template
  sensors:
    aqi_carbon_monoxide:
      friendly_name: Carbon Monoxide
      icon_template: mdi:fire
      unit_of_measurement: 'PPM'
      entity_id:
        - sensor.waqi_rivesud_de_montreal_quebec_canada
        - sensor.waqi_longueuil__secteur_du_parc_oceanie_brossard_quebec_canada
      value_template: >-
        {% set levels = 0 %}
        {% set counter = 0 %}
        {% if states('sensor.waqi_rivesud_de_montreal_quebec_canada') != "unknown" and states.sensor.waqi_rivesud_de_montreal_quebec_canada.attributes.co is defined %}
          {% set levels = levels + states.sensor.waqi_rivesud_de_montreal_quebec_canada.attributes.co %}
          {% set counter = counter + 1 %}
        {% endif %}
        {% if states('sensor.waqi_longueuil__secteur_du_parc_oceanie_brossard_quebec_canada') != "unknown" and states.sensor.waqi_longueuil__secteur_du_parc_oceanie_brossard_quebec_canada.attributes.co is defined %}
          {% set levels = levels + states.sensor.waqi_longueuil__secteur_du_parc_oceanie_brossard_quebec_canada.attributes.co %}
          {% set counter = counter + 1 %}
        {% endif %}

        {% if counter > 0 %}
          {{ (levels / counter) | round }}
        {% else %}
          unknown
        {% endif %}

    aqi_carbon_monoxide_friendly:
      friendly_name: Carbon Monoxide
      icon_template: mdi:fire
      entity_id:
        - sensor.aqi_carbon_monoxide
      value_template: >-
        {% set co = states('sensor.aqi_carbon_monoxide') | int(-1) %}

        {% if co < 0 %}
          unknown
        {% elif 0 <= co <= 50 %}
          Good
        {% elif 51 <= co <= 100 %}
          Moderate
        {% elif 101 <= co <= 150 %}
          Unhealthy for Sensitive Groups
        {% elif 151 <= co <= 200 %}
          Unhealthy
        {% elif 201 <= co <= 300 %}
          Very Unhealthy
        {% elif 301 <= co %}
          Hazardous
        {% else %}
          N/A
        {% endif %}


#
# Dark Sky: Ultraviolet rays
#
# see: https://en.wikipedia.org/wiki/Ultraviolet_index
#
- platform: template
  sensors:
    uv:
      friendly_name: UV Index
      icon_template: mdi:sunglasses
      entity_id:
        - sensor.dark_sky_uv_index
      value_template: >-
        {{ states('sensor.dark_sky_uv_index') }}

    uv_friendly:
      friendly_name: UV Index
      icon_template: mdi:sunglasses
      entity_id:
        - sensor.dark_sky_uv_index
      value_template: >-
        {% set uv = states('sensor.dark_sky_uv_index') | float %}

        {% if 0 <= uv < 3 %}
          Low
        {% elif 3 <= uv < 6 %}
          Moderate
        {% elif 6 <= uv < 8 %}
          High
        {% elif 8 <= uv < 11 %}
          Very high
        {% elif 11 <= uv %}
          Extreme
        {% else %}
          N/A
        {% endif %}
