#
# Bing Wallpaper
#
# Used for wallpaper cameras.
#
# @see /cameras/wallpapers.yaml
#
# @link https://bing.com
#
- platform: rest
  name: Bing Wallpaper
  resource: http://www.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1&mkt=en-US
  icon_template: mdi:link-variant
  scan_interval: 3600
  value_template: >-
    {% if value_json and value_json.images[0] and value_json.images[0].urlbase %}
      {{ value_json.images[0].urlbase }}
    {% endif %}

- platform: rest
  name: Bing Wallpaper Info
  resource: http://www.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1&mkt=en-US
  icon_template: mdi:information-outline
  entity_id:
    - sensor.bing_wallpaper
  value_template: >-
    {% if value_json and value_json.images[0] and value_json.images[0].copyright %}
      {{ value_json.images[0].copyright.split(' (')[0] }}
    {% endif %}


#
# NASA's Astronomy Picture of the Day
#
# Used for wallpaper cameras.
#
# @see /cameras/wallpapers.yaml
#
# @link https://apod.nasa.gov
#
- platform: scrape
  name: APOD
  resource: https://apod.nasa.gov/apod/astropix.html
  scan_interval: 3600
  select: "center a img"
  attribute: "src"

- platform: scrape
  name: APOD Info
  resource: https://apod.nasa.gov/apod/astropix.html
  scan_interval: 3600
  select: "center > b"


#
# Environment Canada radar location
#
# Used as privacy plaholder for the Environment Canada radar map.
#
# @see /cameras/environment_canada.yaml
#
- platform: template
  sensors:
    environment_canada_radar:
      friendly_name: Environment Canada Radar
      value_template: !secret environment_canada_radar
