#
# Bing Wallpaper
#
- platform: rest
  resource: http://www.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1&mkt=en-US
  name: Bing Wallpaper
  icon_template: mdi:link-variant
  scan_interval: 3600
  value_template: "http://www.bing.com{{ value_json.images[0].urlbase }}_800x600.jpg"

- platform: rest
  resource: http://www.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1&mkt=en-US
  name: Bing Wallpaper Info
  icon_template: mdi:information-outline
  entity_id:
    - sensor.bing_wallpaper
  value_template: "{{ value_json.images[0].copyright.split(' (')[0] }}"


#
# Environment Canada radar maps
#

# Environment Canada radar location (placeholder)
- platform: template
  sensors:
    environment_canada_radar:
      friendly_name: Environment Canada Radar
      value_template: !secret environment_canada_radar

# Environment Canada radar image URLs.
# Radar images are batch created every 10 minutes on the dot, but can take up
# to 10 minutes to be generated and stored on Environment Canada's servers.
# We therefore fetch the image for the last batch, which may be up
# to 19 minute stale.
- platform: template
  sensors:
    environment_canada_rain:
      friendly_name: Environment Canada Rain
      entity_id:
        - sensor.time
      icon_template: mdi:link-variant
      value_template: >-
        {% set location = states('sensor.environment_canada_radar') %}
        {% set offset = 10*60 %}
        {% set timestamp = as_timestamp(utcnow()) - offset %}
        {% set minutes = ((timestamp | timestamp_custom('%M', false)) | int / 10) | int | string + '0' %}
        {% set datestamp = timestamp | timestamp_custom('%Y%m%d%H', false) + minutes %}

        http://dd.weather.gc.ca/radar/PRECIPET/GIF/{{location}}/{{datestamp}}_{{location}}_PRECIPET_RAIN.gif

    environment_canada_snow:
      friendly_name: Environment Canada Snow
      entity_id:
        - sensor.time
      icon_template: mdi:link-variant
      value_template: >-
        {% set location = states('sensor.environment_canada_radar') %}
        {% set offset = 10*60 %}
        {% set timestamp = as_timestamp(utcnow()) - offset %}
        {% set minutes = ((timestamp | timestamp_custom('%M', false)) | int / 10) | int | string + '0' %}
        {% set datestamp = timestamp | timestamp_custom('%Y%m%d%H', false) + minutes %}

        http://dd.weather.gc.ca/radar/PRECIPET/GIF/{{location}}/{{datestamp}}_{{location}}_PRECIPET_SNOW.gif
