#
# Bed wash lights effects
#
- platform: template
  sensors:
    bed_effect_loaded:
      friendly_name: Bed Effect Loaded
      value_template: >-
        {% if is_state('group.bed', 'on') %}
          {{ states('variable.bed_effect') }}
        {% endif %}


#
# Ceiling wash lights effects
#
- platform: template
  sensors:
    ceiling_effect_loaded:
      friendly_name: Ceiling Effect Loaded
      value_template: >-
        {% if is_state('group.ceiling', 'on') %}
          {{ states('variable.ceiling_effect') }}
        {% endif %}


#
# Nanoleaf Aurora effect and brightness
#
- platform: mqtt
  name: Aurora Effect
  state_topic: 'home/aurora/effect'
  value_template: '{{ value_json.name }}'
  qos: 1

- platform: mqtt
  name: Aurora Brightness
  state_topic: 'home/aurora/effect'
  value_template: '{{ value_json.brightness }}'
  qos: 1

- platform: template
  sensors:
    aurora_effect_loaded:
      friendly_name: Aurora Effect Loaded
      value_template: '{{ states.light.aurora.attributes.effect }}'
