#
# Fast.com
#
# - platform: fastdotcom
#   hour:
#     - 3
#     - 9
#     - 15
#     - 21
#   minute:
#     - 15


#
# Speedtest.net
#
- platform: speedtest
  monitored_conditions:
    - ping
    - download
    - upload
  server_id: !secret speedtest_server_id
  hour:
    - 0
    - 6
    - 12
    - 18
  minute:
    - 15
