#
# AcuRite battery monitoring
#
# This device only has two power state: `OK` (1) and `low` (0). If no signal is
# received we assume that the battery is dead.
#
# @see /rtl4332mqtt/rtl2mqtt.sh
#
# @link https://www.acurite.com/indoor-temperature-sensor-and-humidity-gauge.html
# @link https://home-assistant.io/components/mqtt/
#
- platform: mqtt
  name: Bedroom AcuRite Battery
  state_topic: "home/bedroom/bedroom"
  unit_of_measurement: '%'
  value_template: >-
    {% set battery_level = value_json.battery | default(0) | int %}

    {% if battery_level %}
      100
    {% else %}
      10
    {% endif %}

- platform: template
  sensors:
    bedroom_multisensor_battery:
      friendly_name: Bedroom Multisensor Battery
      unit_of_measurement: '%'
      value_template: >-
        {% set battery_level = states('sensor.bedroom_acurite_battery') | default(0) | int %}

        {{ battery_level }}
      icon_template: >-
        {% set battery_level = states('sensor.bedroom_acurite_battery') | default(0) | int %}

        {% if battery_level > 10 %}
          mdi:battery
        {% elif battery_round == 10 %}
          mdi:battery-10
        {% else %}
          mdi:battery-outline
        {% endif %}


#
# ZWave battery monitoring
#
# @link https://aeotec.com/z-wave-door-window-sensor
# @link https://aeotec.com/z-wave-sensor
#
- platform: template
  sensors:
    front_door_sensor_battery:
      friendly_name: Front Door Sensor Battery
      unit_of_measurement: '%'
      value_template: >-
        {% set battery_level = states.zwave.front_door.attributes.battery_level | default(0) | int %}

        {% if battery_level %}
          {{ battery_level | round }}
        {% else %}
          {{ states('zwave.front_door') }}
        {%- endif %}
      icon_template: >-
        {% set battery_level = states.zwave.front_door.attributes.battery_level | default(0) | int %}
        {% set battery_round = (battery_level / 10) | int * 10 %}

        {% if battery_round >= 100 %}
          mdi:battery
        {% elif battery_round > 0 %}
          mdi:battery-{{ battery_round }}
        {% else %}
          mdi:battery-outline
        {% endif %}

    lounge_multisensor_battery:
      friendly_name: Lounge Multisensor Battery
      unit_of_measurement: '%'
      value_template: >-
        {% set battery_level = states.zwave.lounge_multisensor.attributes.battery_level | default(0) %}

        {% if battery_level %}
          {{ battery_level | round }}
        {% else %}
          {{ states('zwave.lounge_multisensor') }}
        {%- endif %}
      icon_template: >-
        {% set battery_level = states.zwave.lounge_multisensor.attributes.battery_level | default(0) | int %}
        {% set battery_round = (battery_level / 10) | int * 10 %}

        {% if battery_round >= 100 %}
          mdi:battery
        {% elif battery_round > 0 %}
          mdi:battery-{{ battery_round }}
        {% else %}
          mdi:battery-outline
        {% endif %}
