#
# Door status
#
# Returns a comma-separated list of doors currently open.
#
# @see /automations/doors_verify.yaml
#
- platform: template
  sensors:
    doors_status:
      friendly_name: Doors
      friendly_name_template: >-
        {% if is_state('input_boolean.doors_open', 'on') %}
          Doors open
        {% else %}
          External doors
        {% endif %}
      icon_template: >-
        {% if is_state('input_boolean.doors_open', 'on') %}
          mdi:door-open
        {% else %}
          mdi:door-closed
        {% endif %}
      value_template: >-
        {% set dummy = is_state('input_boolean.doors_open', 'on') %}
        {% set value = '' %}
        {% if is_state('binary_sensor.front_door', 'on') %}
          {% set value = value + 'Front Door,' %}
        {% endif %}
        {% set value = value[:-1] %}

        {% if value != '' %}
          {{ value }}
        {% else %}
          Closed
        {% endif %}


#
# Leak detection status
#
# Returns a comma-separated list of locations where leaks are detected.
#
# @see /automations/leak_notify.yaml
#
- platform: template
  sensors:
    leak_location:
      value_template: >-
        {% for entity_id in state_attr('group.leak_sensors', 'entity_id') -%}
          {% if is_state(entity_id, 'on') -%}
            {{ ' ' + state_attr(entity_id, 'friendly_name') }},
          {%- endif %}
        {%- endfor %}

    leak_location_friendly:
      value_template: >-
        {% set value = states('sensor.leak_location') %}

        {{ value[:-1] }}

    leak_status:
      friendly_name: Leaks
      friendly_name_template: >-
        {% if is_state('group.leak_sensors', 'on') %}
          Leak detected
        {% else %}
          Leaks
        {% endif %}
      icon_template: >-
        {% if is_state('group.leak_sensors', 'on') %}
          mdi:pipe-leak
        {% else %}
          mdi:pipe
        {% endif %}
      value_template: >-
        {% set value = states('sensor.leak_location_friendly') %}

        {% if value != '' %}
          {{ value }}
        {% else %}
          Clear
        {% endif %}


#
# Motion detection status
#
# Returns a comma-separated list of locations where motion is detected.
#
- platform: template
  sensors:
    motion_location:
      value_template: >-
        {% set value = '' %}

        {% if is_state('binary_sensor.bedroom_motion', 'on') %}
          {% set value = value + state_attr('binary_sensor.bedroom_motion', 'friendly_name') + '|' %}
        {% endif %}

        {% if is_state('binary_sensor.front_door', 'on') %}
          {% set value = value + state_attr('binary_sensor.front_door', 'friendly_name') + '|' %}
        {% endif %}

        {% if is_state('binary_sensor.kiosk_motion_auto', 'on') %}
          {% set value = value + state_attr('binary_sensor.kiosk_motion_auto', 'friendly_name') + '|' %}
        {% endif %}

        {% if is_state('binary_sensor.lounge_motion', 'on') %}
          {% set value = value + state_attr('binary_sensor.lounge_motion', 'friendly_name') + '|' %}
        {% endif %}

        {% if is_state('binary_sensor.washroom_motion', 'on') %}
          {% set value = value + state_attr('binary_sensor.washroom_motion', 'friendly_name') + '|' %}
        {% endif %}

        {% if is_state('input_boolean.motion_test', 'on') %}
          {% set value = value + state_attr('input_boolean.motion_test', 'friendly_name') + '|' %}
        {% endif %}

        {% set value = value[:-1] %}
        {% set value = value | replace(" Multisensor", "") %}
        {% set value = value | replace(" Sensor", "") %}
        {% set value = value | replace(" Motion", "") %}
        {% set value = value | replace("|", ", ") %}

        {{ value }}

    motion_status:
      friendly_name: Motion
      friendly_name_template: >-
        {% if is_state('group.motion_sensors', 'on') %}
          Motion detected
        {% else %}
          Motion
        {% endif %}
      icon_template: >-
        {% if is_state('group.motion_sensors', 'on') %}
          mdi:run
        {% else %}
          mdi:radar
        {% endif %}
      value_template: >-
        {% set value = states('sensor.motion_location') %}

        {% if value != '' %}
          {{ value }}
        {% else %}
          Clear
        {% endif %}


#
# Smoke detection status
#
# @see /automations/siren_notify.yaml
# @see /misc/binary_sensors.yaml
#
# @link https://discoverecolink.com/product/firefighter-wireless-smoke-co-audio-sensor/
#
- platform: template
  sensors:
    smoke_location:
      value_template: >-
        {% set value = '' %}

        {% if is_state('binary_sensor.siren_monitor_smoke', 'on') %}
          {% set value = value + state_attr('binary_sensor.siren_monitor_smoke', 'friendly_name') + '|' %}
        {% endif %}

        {% if is_state('input_boolean.smoke_test', 'on') %}
          {% set value = value + state_attr('input_boolean.smoke_test', 'friendly_name') + '|' %}
        {% endif %}

        {% set value = value[:-1] %}
        {% set value = value | replace(" Multisensor", "") %}
        {% set value = value | replace(" Sensor", "") %}
        {% set value = value | replace(" Motion", "") %}
        {% set value = value | replace("|", ", ") %}

        {{ value }}

    smoke_status:
      friendly_name: Smoke
      friendly_name_template: >-
        {% if is_state('group.smoke_sensors', 'on') %}
          Smoke detected
        {% else %}
          Smoke
        {% endif %}
      icon_template: >-
        {% if is_state('group.smoke_sensors', 'on') %}
          mdi:alarm-bell
        {% else %}
          mdi:smoke-detector
        {% endif %}
      value_template: >-
        {% set value = states('sensor.smoke_location') %}

        {% if value != '' %}
          {{ value }}
        {% else %}
          Clear
        {% endif %}


#
# Tampering status
#
# Returns a comma-separated list of perimeter devices being tampered with.
#
# @see /automations/modes/tamper_start.yaml
# @see /misc/variables.yaml
#
- platform: template
  sensors:
    tamper_status:
      friendly_name: Tampering
      friendly_name_template: >-
        {% if is_state('input_boolean.tamper_detected', 'on') %}
          Tampering detected
        {% else %}
          Tampering
        {% endif %}
      icon_template: >-
        {% if is_state('input_boolean.tamper_detected', 'on') %}
          mdi:home-alert
        {% else %}
          mdi:security-home
        {% endif %}
      value_template: >-
        {% set dummy = is_state('input_boolean.tamper_detected', 'on') %}
        {% if not is_state('variable.tamper_detected', 'False') %}
          {{ states('variable.tamper_detected') }}
        {% else %}
          Clear
        {% endif %}
