# CPU speed
# - platform: cpuspeed
#   # name: CPU Speed

# CPU temperature
- platform: command_line
  name: CPU Temp
  command: cat /sys/class/thermal/thermal_zone0/temp
  unit_of_measurement: °C
  value_template: '{{ (value | multiply(0.001)) | round(0) }}'
  icon_template: mdi:thermometer

# Hass uptime
- platform: uptime
  name: Uptime HASS
  unit_of_measurement: hours

# System monitor
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: ipv4_address
      arg: eth0
    - type: memory_use_percent
    - type: processor_use
    - type: since_last_boot

# Version checker
- platform: command_line
  name: "HASS version"
  command: "cat /config/.HA_VERSION"

# Friendly version report (useful for HADashboard)
- platform: template
  sensors:
    home_assistant_version_string:
      friendly_name: Home Assistant version string
      icon_template: mdi:update
      value_template: >-
        HASS v{{ states('sensor.hass_version') }}
    update_available:
      friendly_name: Update available
      icon_template: mdi:update
      value_template: >-
        {% if is_state('input_boolean.update_available', 'on') %}
          Update available.
        {% endif %}

# Free disk space
- platform: template
  sensors:
    disk_free_percent:
      friendly_name: Disk free /home
      icon_template: mdi:harddisk
      unit_of_measurement: '%'
      value_template: >-
        {{ (100 - states.sensor.disk_used_home.state|float) | int }}

# Free RAM space
- platform: template
  sensors:
    ram_free_percent:
      friendly_name: RAM free
      icon_template: mdi:memory
      unit_of_measurement: '%'
      value_template: >-
        {{ (100 - states.sensor.ram_used.state|float) | int }}

# Home Assistant uptime
- platform: template
  sensors:
    uptime_hass_friendly:
      friendly_name: Hass uptime
      icon_template: mdi:home-assistant
      value_template: >-
        {% set uptime = states.sensor.uptime_hass.state|float %}
        {% set time = (3600 * uptime) | int %}
        {% set minutes = ((time % 3600) / 60) | int %}
        {% set hours = ((time % 86400) / 3600) | int %}
        {% set days = (time / 86400) | int %}

        {% if time < 60 %}
          {{ time }} seconds
        {% else %}
          {%- if days > 0 -%}
            {%- if days == 1 -%}
              1 day
            {%- else -%}
              {{ days }} days
            {%- endif -%}
          {%- endif -%}
          {%- if hours > 0 and days < 7 -%}
            {%- if days > 0 -%}
              {{ ', ' }}
            {%- endif -%}
            {%- if hours == 1 -%}
              1 hour
            {%- else -%}
              {{ hours }} hours
            {%- endif -%}
          {%- endif -%}
          {%- if days == 0 and minutes > 0 -%}
            {%- if hours > 0 -%}
              {{ ', ' }}{{ minutes }} min
            {%- else -%}
              {%- if minutes == 1 -%}
                1 minute
              {%- else -%}
                {{ minutes }} minutes
              {%- endif -%}
            {%- endif -%}
          {%- endif -%}
        {% endif %}

# Host uptime
- platform: template
  sensors:
    uptime_host:
      friendly_name: Server uptime
      icon_template: mdi:server
      value_template: >-
        {% set slb = states.sensor.since_last_boot.state.split(' ') %}
        {% set count = slb | length %}
        {% set hms = slb[count - 1] %}
        {% set hms_trimmed = hms.split('.')[0] %}
        {% set hms_split = hms_trimmed.split(':') %}
        {% set seconds = hms_split[2] | int %}
        {% set minutes = hms_split[1] | int %}
        {% set hours = hms_split[0] | int %}
        {% set days = slb[0]|int %}

        {% if hours == 0 and minutes == 0 %}
          {{ time }} seconds
        {% else %}
          {%- if days > 0 -%}
            {%- if days == 1 -%}
              1 day
            {%- else -%}
              {{ days }} days
            {%- endif -%}
          {%- endif -%}
          {%- if hours > 0 and days < 7 -%}
            {%- if days > 0 -%}
              {{ ', ' }}
            {%- endif -%}
            {%- if hours == 1 -%}
              1 hour
            {%- else -%}
              {{ hours }} hours
            {%- endif -%}
          {%- endif -%}
          {%- if days == 0 and minutes > 0 -%}
            {%- if hours > 0 -%}
              {{ ', ' }}{{ minutes }} min
            {%- else -%}
              {%- if minutes == 1 -%}
                1 minute
              {%- else -%}
                {{ minutes }} minutes
              {%- endif -%}
            {%- endif -%}
          {%- endif -%}
        {% endif %}

