#
# Version checker
#
- platform: version


#
# System monitor
#
- platform: systemmonitor
  scan_interval: 60
  resources:
    - type: disk_use_percent
      arg: /home
    - type: ipv4_address
      arg: eth0
    - type: memory_use_percent
    - type: processor_use
    - type: since_last_boot


#
# Friendly version report (useful for HADashboard)
#
- platform: template
  sensors:
    version_friendly:
      friendly_name: Home Assistant version
      icon_template: mdi:update
      entity_id:
        - sensor.current_version
      value_template: >-
        {% if states('sensor.current_version') != "unknown" %}
          HASS v{{ states('sensor.current_version') }}
        {% else %}
          HASS
        {% endif %}

    update_available:
      friendly_name: Update available
      icon_template: mdi:update
      entity_id:
        - input_boolean.update_available
      value_template: >-
        {% if is_state('input_boolean.update_available', 'on') %}
          Update available.
        {% endif %}


#
# Available disk space
#
- platform: template
  sensors:
    disk_free_percent:
      friendly_name: Disk free /home
      icon_template: mdi:harddisk
      unit_of_measurement: '%'
      entity_id:
        - sensor.disk_used_home
      value_template: >-
        {{ (100 - states('sensor.disk_used_home')|float) | int }}


#
# Available RAM space
#
- platform: template
  sensors:
    ram_free_percent:
      friendly_name: RAM free
      icon_template: mdi:memory
      unit_of_measurement: '%'
      entity_id:
        - sensor.ram_used
      value_template: >-
        {{ (100 - states('sensor.ram_used')|float) | int }}


#
# Host uptime
#
- platform: template
  sensors:
    uptime_host:
      friendly_name: Server uptime
      icon_template: mdi:server
      entity_id:
        - sensor.since_last_boot
      value_template: >-
        {% set slb = states('sensor.since_last_boot').split(' ') %}
        {% set count = slb | length %}
        {% set hms = slb[count - 1] %}
        {% set hms_trimmed = hms.split('.')[0] %}
        {% set hms_split = hms_trimmed.split(':') %}
        {% set seconds = hms_split[2] | int %}
        {% set minutes = hms_split[1] | int %}
        {% set hours = hms_split[0] | int %}
        {% set days = slb[0]|int %}

        {% if hours == 0 and minutes == 0 %}
          {{ time }} seconds
        {% else %}
          {%- if days > 0 -%}
            {%- if days == 1 -%}
              1 day
            {%- else -%}
              {{ days }} days
            {%- endif -%}
          {%- endif -%}
          {%- if hours > 0 and days < 7 -%}
            {%- if days > 0 -%}
              {{ ', ' }}
            {%- endif -%}
            {%- if hours == 1 -%}
              1 hour
            {%- else -%}
              {{ hours }} hours
            {%- endif -%}
          {%- endif -%}
          {%- if days == 0 and minutes > 0 -%}
            {%- if hours > 0 -%}
              {{ ', ' }}{{ minutes }} min
            {%- else -%}
              {%- if minutes == 1 -%}
                1 minute
              {%- else -%}
                {{ minutes }} minutes
              {%- endif -%}
            {%- endif -%}
          {%- endif -%}
        {% endif %}


#
# Hass uptime
#
- platform: uptime
  name: Uptime
  scan_interval: 60
  unit_of_measurement: hours

- platform: template
  sensors:
    uptime_friendly:
      friendly_name: Uptime
      icon_template: mdi:home-assistant
      entity_id:
        - sensor.uptime
      value_template: >-
        {% set uptime = states('sensor.uptime')|float %}
        {% set time = (3600 * uptime) | int %}
        {% set minutes = ((time % 3600) / 60) | int %}
        {% set hours = ((time % 86400) / 3600) | int %}
        {% set days = (time / 86400) | int %}

        {% if time < 60 %}
          {{ time }} seconds
        {% else %}
          {%- if days > 0 -%}
            {%- if days == 1 -%}
              1 day
            {%- else -%}
              {{ days }} days
            {%- endif -%}
          {%- endif -%}
          {%- if hours > 0 and days < 7 -%}
            {%- if days > 0 -%}
              {{ ', ' }}
            {%- endif -%}
            {%- if hours == 1 -%}
              1 hour
            {%- else -%}
              {{ hours }} hours
            {%- endif -%}
          {%- endif -%}
          {%- if days == 0 and minutes > 0 -%}
            {%- if hours > 0 -%}
              {{ ', ' }}{{ minutes }} min
            {%- else -%}
              {%- if minutes == 1 -%}
                1 minute
              {%- else -%}
                {{ minutes }} minutes
              {%- endif -%}
            {%- endif -%}
          {%- endif -%}
        {% endif %}


#
# CPU temperature
#
- platform: command_line
  name: CPU Temp
  scan_interval: 60
  unit_of_measurement: °C
  command: cat /sys/class/thermal/thermal_zone0/temp
  value_template: '{{ (value | multiply(0.001)) | round(0) }}'
  icon_template: mdi:thermometer


#
# Database size
#
# see: https://community.home-assistant.io/t/recorder-purge-function/17154/12
#
- platform: command_line
  name: Database Size
  scan_interval: 600
  command: "du -m /config/home-assistant_v2.db | cut -f1"
  unit_of_measurement: 'MB'


#
# Logfile size
#
# see: https://community.home-assistant.io/t/recorder-purge-function/17154/12
#
- platform: command_line
  name: Logfile Size
  scan_interval: 600
  command: "du -k /config/home-assistant.log | cut -f1"
  unit_of_measurement: 'kB'
