#
# System monitor
#
# Lots of geeky details about the server hardware.
#
# @link https://home-assistant.io/components/sensor.systemmonitor/
#
- platform: systemmonitor
  scan_interval: 60
  resources:
    - type: disk_use_percent
      arg: /home
    - type: disk_free
      arg: /home
    - type: ipv4_address
      arg: eth0
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: memory_use_percent
    - type: memory_free
    - type: processor_use
    - type: since_last_boot


#
# Version
#
# @link https://home-assistant.io/components/sensor.version/
#
- platform: version


#
# Friendly version report
#
# Useful for HADashboard.
#
# @see /appdaemon/dashboards/Status.dash
#
- platform: template
  sensors:
    version_friendly:
      friendly_name: Home Assistant Version
      icon_template: mdi:update
      value_template: >-
        {% if states('sensor.current_version') != "unknown" %}
          HASS {{ states('sensor.current_version') }}
        {% else %}
          HASS
        {% endif %}

    update_available:
      friendly_name: Update Available
      icon_template: mdi:update
      value_template: >-
        {% if states('updater.updater') != "unknown" %}
          Update available: {{ states('updater.updater') }}
        {% endif %}


#
# Disk space
#
# @see /appdaemon/dashboards/Status.dash
# @see /groups/status.yaml
#
- platform: template
  sensors:
    disk_used_percent:
      friendly_name: Disk Used /home
      icon_template: mdi:harddisk
      unit_of_measurement: '%'
      value_template: >-
         {{ states('sensor.disk_used_home') | float | round }}

    disk_free_percent:
      friendly_name: Disk Free /home
      icon_template: mdi:harddisk
      unit_of_measurement: '%'
      value_template: >-
        {{ 100 - states('sensor.disk_used_home') | float | round }}


#
# RAM space
#
# @see /appdaemon/dashboards/Status.dash
# @see /groups/status.yaml
#
- platform: template
  sensors:
    ram_used_percent:
      friendly_name: RAM Used
      icon_template: mdi:memory
      unit_of_measurement: '%'
      value_template: >-
        {{ states('sensor.ram_used') | float | round }}

    ram_free_percent:
      friendly_name: RAM Free
      icon_template: mdi:memory
      unit_of_measurement: '%'
      value_template: >-
        {{ 100 - states('sensor.ram_used') | float | round }}


#
# Host uptime
#
# @see /appdaemon/dashboards/Status.dash
# @see /groups/status.yaml
#
- platform: template
  sensors:
    uptime_host:
      friendly_name: Server Uptime
      icon_template: mdi:server
      value_template: >-
        {% set slb = states('sensor.since_last_boot').split(' ') %}
        {% set count = slb | length %}
        {% set hms = slb[count - 1] %}
        {% set hms_trimmed = hms.split('.')[0] %}
        {% set hms_split = hms_trimmed.split(':') %}
        {% set seconds = hms_split[2] | int %}
        {% set minutes = hms_split[1] | int %}
        {% set hours = hms_split[0] | int %}
        {% set days = slb[0]|int %}

        {% if hours == 0 and minutes == 0 %}
          {{ time }} seconds
        {% else %}
          {%- if days > 0 -%}
            {%- if days == 1 -%}
              1 day
            {%- else -%}
              {{ days }} days
            {%- endif -%}
          {%- endif -%}
          {%- if hours > 0 and days < 7 -%}
            {%- if days > 0 -%}
              {{ ', ' }}
            {%- endif -%}
            {%- if hours == 1 -%}
              1 hour
            {%- else -%}
              {{ hours }} hours
            {%- endif -%}
          {%- endif -%}
          {%- if days == 0 and minutes > 0 -%}
            {%- if hours > 0 -%}
              {{ ', ' }}{{ minutes }} min
            {%- else -%}
              {%- if minutes == 1 -%}
                1 minute
              {%- else -%}
                {{ minutes }} minutes
              {%- endif -%}
            {%- endif -%}
          {%- endif -%}
        {% endif %}


#
# Home Assistant uptime
#
# For Home Assistant process/container.
#
# @see /appdaemon/dashboards/Status.dash
# @see /groups/status.yaml
#
# @link https://home-assistant.io/components/sensor.uptime/
#
- platform: uptime
  name: Uptime
  scan_interval: 60
  unit_of_measurement: hours

- platform: template
  sensors:
    uptime_friendly:
      friendly_name: Uptime
      icon_template: mdi:home-assistant
      value_template: >-
        {% set uptime = states('sensor.uptime')|float %}
        {% set time = (3600 * uptime) | int %}
        {% set minutes = ((time % 3600) / 60) | int %}
        {% set hours = ((time % 86400) / 3600) | int %}
        {% set days = (time / 86400) | int %}

        {% if time < 60 %}
          {{ time }} seconds
        {% else %}
          {%- if days > 0 -%}
            {%- if days == 1 -%}
              1 day
            {%- else -%}
              {{ days }} days
            {%- endif -%}
          {%- endif -%}
          {%- if hours > 0 and days < 7 -%}
            {%- if days > 0 -%}
              {{ ', ' }}
            {%- endif -%}
            {%- if hours == 1 -%}
              1 hour
            {%- else -%}
              {{ hours }} hours
            {%- endif -%}
          {%- endif -%}
          {%- if days == 0 and minutes > 0 -%}
            {%- if hours > 0 -%}
              {{ ', ' }}{{ minutes }} min
            {%- else -%}
              {%- if minutes == 1 -%}
                1 minute
              {%- else -%}
                {{ minutes }} minutes
              {%- endif -%}
            {%- endif -%}
          {%- endif -%}
        {% endif %}


#
# CPU cores count
#
# Useful to get an idea of the system load. Scan interval is set to daily,
# because it's quite unlikely that cores change ...often unless one plays with
# the VM's settings all the time.
#
# @see /customize.yaml
#
# @link https://home-assistant.io/components/sensor.command_line/
#
- platform: command_line
  name: CPU Cores
  scan_interval: 86400
  command: "grep 'model name' /proc/cpuinfo | wc -l"
  icon_template: mdi:chip


#
# CPU temperature
#
# @see /appdaemon/dashboards/Status.dash
# @see /groups/status.yaml
#
# @link https://home-assistant.io/components/sensor.command_line/
#
- platform: command_line
  name: CPU Temp
  scan_interval: 60
  unit_of_measurement: °C
  command: cat /sys/class/thermal/thermal_zone0/temp
  icon_template: mdi:thermometer
  value_template: '{{ (value | multiply(0.001)) | round(0) }}'


#
# Database size
#
# @see /appdaemon/dashboards/Status.dash
# @see /groups/status.yaml
#
# @link https://community.home-assistant.io/t/recorder-purge-function/17154/12
# @link https://home-assistant.io/components/sensor.command_line/
#
- platform: command_line
  name: Database Size
  scan_interval: 600
  unit_of_measurement: 'MB'
  command: "du -m /config/home-assistant_v2.db | cut -f1"


#
# Log file size
#
# @see /appdaemon/dashboards/Status.dash
# @see /groups/status.yaml
#
# @link https://community.home-assistant.io/t/recorder-purge-function/17154/12
# @link https://home-assistant.io/components/sensor.command_line/
#
- platform: command_line
  name: Logfile Size
  scan_interval: 600
  unit_of_measurement: 'kB'
  command: "du -k /config/home-assistant.log | cut -f1"
