- platform: generic
  name: Environment Canada Rain
  entity_id:
    - sensor.environment_canada_rain
  still_image_url: >-
    {{ states('sensor.environment_canada_rain')}}
  content_type: image/gif

- platform: generic
  name: Environment Canada Snow
  entity_id:
    - sensor.environment_canada_snow
  still_image_url: >-
    {{ states('sensor.environment_canada_snow')}}
  content_type: image/gif
