- platform: generic
  name: NOAA Shortwave
  still_image_url: http://www.ssd.noaa.gov/goes/east/eaus/ir2-animated.gif
  content_type: image/gif

- platform: generic
  name: NOAA Water Vapour
  still_image_url: http://www.ssd.noaa.gov/goes/east/eaus/wv-animated.gif
  content_type: image/gif
