#
# U.S. National Oceanic and Atmospheric Administration satellite imaging
#
# GOES-East Northeast region.
# Scan interval is set to every 3 hours, because air masses move slowly as
# seen from space.
#
# @see /appdaemon/dashboards/Weather.dash
# @see /groups/weather.yaml
#
# @link https://www.star.nesdis.noaa.gov/GOES/GOES16_sectors.php?sector=ne
#
- platform: generic
  name: NOAA GeoColor
  scan_interval: 10800
  content_type: image/jpeg
  still_image_url: https://cdn.star.nesdis.noaa.gov/GOES16/ABI/SECTOR/ne/GEOCOLOR/600x600.jpg


- platform: generic
  name: NOAA Water Vapour
  scan_interval: 10800
  content_type: image/jpeg
  still_image_url: https://cdn.star.nesdis.noaa.gov/GOES16/ABI/SECTOR/ne/10/600x600.jpg
