#
# U.S. National Oceanic and Atmospheric Administration satellite imaging
#
# GOES-East Northeast region
#
# see: https://www.star.nesdis.noaa.gov/GOES/GOES16_sectors.php?sector=ne
#
- platform: generic
  name: NOAA GeoColor
  scan_interval: 10800
  still_image_url: https://cdn.star.nesdis.noaa.gov/GOES16/ABI/SECTOR/ne/GEOCOLOR/600x600.jpg
  content_type: image/jpeg

- platform: generic
  name: NOAA Water Vapour
  scan_interval: 10800
  still_image_url: https://cdn.star.nesdis.noaa.gov/GOES16/ABI/SECTOR/ne/10/600x600.jpg
  content_type: image/jpeg

# - platform: generic
#   name: NOAA Shortwave
#   scan_interval: 10800
#   still_image_url: http://www.ssd.noaa.gov/goes/east/eaus/ir2-animated.gif
#   content_type: image/gif

# - platform: generic
#   name: NOAA Water Vapour
#   scan_interval: 10800
#   still_image_url: http://www.ssd.noaa.gov/goes/east/eaus/wv-animated.gif
#   content_type: image/gif
