#
# Bing daily wallpaper
#
# @see /appdaemon/dashboards/Main.dash
# @see /groups/default.yaml
# @see /sensors/camera.yaml
#
# @link https://bing.com
# @link https://www.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1&mkt=en-US
#
- platform: generic
  name: Bing Wallpaper
  limit_refetch_to_url_change: true
  content_type: image/jpg
  still_image_url: >-
    {% if states('sensor.bing_wallpaper') != 'unknown' and states.sensor.bing_wallpaper.attributes.images[0] %}
      {% set path = states.sensor.bing_wallpaper.attributes.images[0].urlbase %}

      https://www.bing.com{{ path }}_800x600.jpg
    {% else %}
      {% set port = states('sensor.server_port') | int %}

      http://127.0.0.1:{{ port }}/local/images/wallpaper-1.jpg
    {% endif %}


#
# NASA's Astronomy picture of the day
#
# Supports images and YouTube thumbnails, but does not handle Vimeo images as
# that would require an extra REST query.
#
# @see /appdaemon/dashboards/Main.dash
# @see /sensors/camera.yaml
#
# @link https://api.nasa.gov/api.html#apod
# @link https://apod.nasa.gov
#
- platform: generic
  name: Astronomy Picture of the Day
  limit_refetch_to_url_change: true
  content_type: image/jpg
  still_image_url: >-
    {% set image = '' %}

    {% if states('sensor.apod') != 'unknown' and states.sensor.apod.attributes.url %}
      {% set url = states.sensor.apod.attributes.url %}

      {% if states.sensor.apod.attributes.media_type == 'video' %}
        {% if 'youtube.com' in url %}
          {% set video = url.split('/')[4].split('?')[0] %}
          {% set image = 'https://img.youtube.com/vi/' + video + '/hqdefault.jpg' %}
        {% endif %}
      {% else %}
        {% set image = states.sensor.apod.attributes.url %}
      {% endif %}
    {% else %}
      {% set port = states('sensor.server_port') | int %}

      {% set image = 'http://127.0.0.1:' + port + '/local/images/wallpaper-2.jpg' %}
    {% endif %}

    {{ image }}
