#
# Bing daily wallpaper
#
# @see /appdaemon/dashboards/Main.dash
# @see /groups/default.yaml
# @see /sensors/images.yaml
#
- platform: generic
  name: Bing Wallpaper
  still_image_url: >-
    http://www.bing.com{{ states('sensor.bing_wallpaper') }}_800x600.jpg
  content_type: image/jpg

#
# NASA's Astronomy picture of the day
#
# @see /appdaemon/dashboards/Main.dash
# @see /sensors/images.yaml
#
- platform: generic
  name: Astronomy Picture of the Day
  still_image_url: >-
    https://apod.nasa.gov/apod/{{ states('sensor.apod') }}
  content_type: image/jpg
